#[picamera]
FRAMERATE = 30
RESOLUTION = (320, 240)

#[TCPserver]
SEND2TCP = True
TCP_IP = '192.168.0.11'
TCP_PORT = 5005
BUFFER_SIZE = 60

#[TrackerSettings]
SHOW = True
SHOW_CIRCLE = True
SHOW_PATH = True
SHOW_COORDINATES = True
SHOW_SCREEN_CENTER = True
FILTER_LOWER = (57, 165, 39)
FILTER_UPPER = (100, 255, 255)
if not SHOW:
    SHOW_CIRCLE = False
    SHOW_PATH = False
    SHOW_COORDINATES = False
    SHOW_SCREEN_CENTER = False


